### ISSUE TITLE
SRS:  T1 not used

### ISSUE THREAD

**Issue by palmerst** [MaXiaoye/cas741#10]
T1 (Conservation of mechanical energy) doesn't appear to be used anywhere.  You note in T1 that it is referenced by IM2, but this doesn't appear to be the case.

**Comment by MaXiaoye** [comment]
Hi Steven,

Actually T1 is the law that IM2 follows.
T1 doesn't appear in equations however pieces moving in Uniformly accelerated motion in the air obey T1. That's why I say it is referenced by IM2.

Best Regards,
Marshall
