### ISSUE TITLE
SRS:  What is potential energy?

### ISSUE THREAD

**Issue by palmerst** [MaXiaoye/cas741#11]
You mention potential energy in a few places.  What potential energy are you referring to?  Gravitational, elastic, chemical, etc.?  I assume it's just gravitational, but this isn't explicitly stated anywhere.

**Comment by MaXiaoye** [comment]
Yes Steven,
For potential energy I only consider gravitational energy in this project.
I will make it more explicit.

Best Regards,
Marshall
