### ISSUE TITLE
SRS:  How do airborn particles lose energy?

### ISSUE THREAD

**Issue by palmerst** [MaXiaoye/cas741#12]
Based on your assumptions and models/definitions, it isn't clear how an airborn fragment ever loses energy and stops moving.  What happens when a fragment hits the ground/surface?  Is there deflection with an inversion of the z-velocity, where the piece bounces back into the air?  If it does deflect, what is the efficiency?  Since you assume there is no drag force in the air, without deflection losses, the fragment will never "settle" to the ground plane and be halted via friction.

**Comment by MaXiaoye** [comment]
Hi Steven,

Thanks good catch !
Actually airborn particles will be generated in real explosion.
However in this project I consider they are too hard to be controlled.
I think in real explosion the airborn has random shapes and motions and they have different TM and IM from normal pieces. For example they are seriously influenced by air friction.
So I ignore airborn in my project in A3. I consider airborn same as powders.

Best Regards,
Marshall

**Comment by smiths** [comment]
Did you make changes in your SRS to reflect this clarification?  You shouldn't close an issue until it is completely dealt with.

**Comment by MaXiaoye** [comment]
Dear Dr.Smith,

Indeed I ignore airborn particles in this project and put this in A3.
I should make it more explicit.
So I upload a new version ef255091e97425018078111b57e5e64fd58f64b7 by updating A3 more explicit. 
I will notice including hash of commit. :)
Thank you for your comments.

Best Regards,
Marshall
