### ISSUE TITLE
SRS:  Undefined specification parameters

### ISSUE THREAD

**Issue by palmerst** [MaXiaoye/cas741#15]
The specification parameters L<sub>min</sub> , L<sub>max</sub> , μ<sub>min</sub> , μ<sub>max</sub> are not defined anywhere.

**Comment by MaXiaoye** [comment]
Thank you for pointing this out Steven.
I update them in next version.

Best Regards,
Marshall

**Comment by smiths** [comment]
@MaXiaoye, in the future, please include the hash of the commit that closes the issue.  This provides greater flexibility so that someone can verify your changes.

**Comment by MaXiaoye** [comment]
Thank you for your comments professor !  
My fault. I will include the hash in the future :)
For this commit the hash is bac94ca02b1715798cd6cc2a84aaf231c64f5efa

Best Regards,
Marshall
