### ISSUE TITLE
Add figures to repo and correct paths in SRS

### ISSUE THREAD

**Issue by smiths** [MaXiaoye/cas741#16]
Please add the figures under version control and correct the path to the figures in the SRS.  As it is right now, the SRS cannot be compiled.

**Comment by MaXiaoye** [comment]
Thank you professor ! I was careless that figure's path is hardcopy in SRS !
I correct the path and upload figure file in 17228145603e45ba0b2c16f3bd6367d27c9dfa24

Best Regards,
Marshall

**Comment by smiths** [comment]
Great!  I can now compile your document.  😄
