### ISSUE TITLE
Comments VnV  #2 - What is happening if a piece goes to the point (0,0,0) ?

### ISSUE THREAD

**Issue by slimpotatoes** [MaXiaoye/cas741#19]
You might notice here my lack of knowledge on how unity3D works but I will still ask my question :p.

I assume that your software is going to interface with unity3D multiple times through the explosion. Explosion starts and unity3D ask your software what should be the position of each piece at t1. Your software answers to unity3D by providing the new position. Then I think that the movement of each piece is displayed to the gamer and unity3D comes back again asking now the position of each piece at t2 and your software redo the same thing until the explosion is considered finished. 

I see in the software that for the angle calculation you use consider ratios of the coordinates of the center of gravity. It is possible at some point that the center of gravity is located at (0,0,0). You have a "divide by 0" issue and I don't see what the output is supposed to be in that case.

**Comment by MaXiaoye** [comment]
Let me describe on a top level how my software display breaking effect to us. :)  You may know from my reply for issue one that my “software” is actually a script that can be attached to 3D object in Unity3D. (This can be made into a plug-in afterward). Let’s say in unity I create a new cube object in the scene, then I attach the script to it and provide all necessary inputs(For now I just do input by modifying codes). Then I click the button “launch” (can also be called generate or start etc. Just means start the “game”). Then I can see the whole process of the “explosion” and how pieces are moving just like an animation. Unity provides time t and you can see in instance models how I calculate displacements of pieces relying on t. So I would say my codes control how those objects(pieces) work directly.
Unity interface with my codes frame by frame (We can consider it as at any time :) ) by calling a function called “update” (this is provided by unity). So in simple words, game developers needs to put their codes (calculation codes that related to time t) into “update” to interface with unity to control objects moving in the scene. 

E.g: I write this line in update (The game actually can’t work for just one line like this, just an abstract example :p )

object.translate(5*delta_t,0,0)

Translate just means move here, delta_t means gap between each frame that is very very tiny period.
Then what happens after I click “launch” is that the object keep moving in speed 5 towards x direction until I click “stop” button.

Hope my description helps more or less for you to know how unity works :p. Oh let’s back to your comments for (0,0,0), thanks for this catching ! Actually I didn’t notice this problem. I will think it over how to solve this :).

**Comment by MaXiaoye** [comment]
Fix in 952bd56f7bde2c351f47c79cec18b6d3fafc3ccd
