### ISSUE TITLE
Please delete the comments from the problem statement

### ISSUE THREAD

**Issue by smiths** [MaXiaoye/cas741#2]
https://github.com/MaXiaoye/cas741/blob/dd1dc1a5e51b37a25325757c14da22ce772de226/BlankProjectTemplate/Doc/ProblemStatement/ProblemStatement.tex#L51

**Comment by MaXiaoye** [comment]
Dear Dr.Smith,

I have updated my PS as our discussion.
Major modifications as following:

"
This project concentrates on calculation while HCI or GUI are not important parts. Applied force is decided in codes in advance as input and pieces movement is the output after calculation. 
"
@smiths 
https://github.com/MaXiaoye/cas741/blob/master/BlankProjectTemplate/Doc/ProblemStatement/ProblemStatement.pdf

Best Regards,
Marshall

**Comment by smiths** [comment]
Looks like a good start.  I approve your problem statement.
