### ISSUE TITLE
Comments VnV  #3 - System test proposal - Free falling of one particule of mass m

### ISSUE THREAD

**Issue by slimpotatoes** [MaXiaoye/cas741#20]
I think that you can be a little more ambitious in your system test design by considering an automated test covering the free falling case of a single particule of mass m. The test could be run automatically at each stage of the implementation.  You don't need to deal with gravity center calculation, angle calculation ( since v0=0) and its a very simple case that your software should easily pass.

**Comment by MaXiaoye** [comment]
Good idea Alexandre ! I will consider an automated test for this. Maybe I need to design modules or even implement some codes then I know how to do this :p

**Comment by MaXiaoye** [comment]
Fix in 58b85cb12f690ed2380299a4a5b6ee9ab2d2f97c
