### ISSUE TITLE
Comments VnV #6 - Energy conservation

### ISSUE THREAD

**Issue by slimpotatoes** [MaXiaoye/cas741#23]
I forgot something :p ... Sorry for that.

I know that the energy conservation is not testing an instance model or a functional requirement directly but I think it's a very good system test. You have a system that has an important constraint with the conservation of energy (in the case of no friction) so you can use it at your advantage. So you could design a test where you use the input provided to your software to calculate the total energy and then your calculated output to calculate again the total energy. Both should match ... if not, something is wrong in the code :). This test can be also be run automatically.

**Comment by MaXiaoye** [comment]
That's a good idea Alex ! 
I will design this test case to check the accuracy !

**Comment by MaXiaoye** [comment]
Upload test cases. Do it in test case for displacement calculation instead of energy calculation. ddaacd9042339f1159759eb694a657af6a798ded
