### ISSUE TITLE
MG: terminology - virtual hardware

### ISSUE THREAD

**Issue by aschaap** [MaXiaoye/cas741#25]
The description for M1 mentions virtual hardware. Perhaps hardware abstraction is more appropriate, since the real hardware is made accessible through the OS rather than virtual hardware as in a virtual machine?

Also in M1's description: hopefully your OS consists of more than one data structure and algorithm - making these plural seems more correct.

**Comment by MaXiaoye** [comment]
Fix in c14ada7d2f8a9bafb275b8dbc1a8437919a73e1f
