### ISSUE TITLE
MG: Spelling/Grammar

### ISSUE THREAD

**Issue by aschaap** [MaXiaoye/cas741#26]
I noticed a few inconsistencies:

M4's description: "Structure" should begin with a small s, "pieces" should be singular, and "unity" should probably somehow signify that you're talking about the Unity3D system.

M9's description: one period at the end of a sentence should suffice.

languagetool.org or Grammarly may help catch similar errors.

**Comment by MaXiaoye** [comment]
Fix in c14ada7d2f8a9bafb275b8dbc1a8437919a73e1f
