### ISSUE TITLE
MG: Uses hierarchy structure

### ISSUE THREAD

**Issue by aschaap** [MaXiaoye/cas741#29]
These seem like steps in a recipe/procedure (which is fine), but are they each single functions that call the next one? And if so, how do both M7 and M6 pass inputs to output? Presumably both need to pass their results to M10, but M10 only functions with both its inputs?

is there (room for) a control module calling each of these modules?

**Comment by MaXiaoye** [comment]
Fix in c14ada7d2f8a9bafb275b8dbc1a8437919a73e1f
