### ISSUE TITLE
Revise your project folders

### ISSUE THREAD

**Issue by smiths** [MaXiaoye/cas741#3]
Please remove the CourseOutline, Lectures etc from your MaXiaoye/cas741 project.  They don't make any sense as part of your project.  Furthermore, rather than have a folder called BlankProjectTemplate, the contents of that folder should be at the top level of your folder hierarchy.  If you have any questions, please respond in the comments below.

**Comment by MaXiaoye** [comment]
Dear Dr.Smith,

Sorry about these unnecessary folders.
I imported the whole repo from gitlab that's why. 
I have revised project folders. 
Contents of "BlankProjectTemplate" are moved to top level.

Best Regards,
Marshall

**Comment by smiths** [comment]
Looks good.
