### ISSUE TITLE
MIS: Incorrect Reference to Program Name (Minor)

### ISSUE THREAD

**Issue by GenevaS** [MaXiaoye/cas741#32]
The first line after the table in the "Notation" section says "The specification of Program Name...". I think this was meant to be replaced by your program's name (Breaking Effect). There is a similar referencing issue later in the same paragraph.

**Comment by MaXiaoye** [comment]
Thank you for pointing this out ! :)
Fixed in 39f790ab5baa1a612643c8b392ed894a865307bb
