### ISSUE TITLE
MIS: Reorganizing Module Information

### ISSUE THREAD

**Issue by GenevaS** [MaXiaoye/cas741#34]
I am looking at the Input Module section as I am writing for your reference:

I think there is some confusion as to where information is supposed to go. The "Exported Access Programs" table is used like a small table of contents for the "Access Routine Semantics" section. The "Exceptions" column of the table should list all of the exception labels that you use in the "Access Routine Semantics" section.

The variables that you have included are probably the state variables (assuming that they are kept indefinitely by your module's logic). 

Your "Author's Notes" could probably be moved to an "Assumptions" section (it would follow the "State Variables" section).

**Comment by MaXiaoye** [comment]
Thank you for the advice Geneva !!
Actually I was not sure a good way before that how to organize so much info in MIS.
Follow your advice
Fixed in 39f790ab5baa1a612643c8b392ed894a865307bb
