### ISSUE TITLE
MIS: Referencing MG Modules in the "Uses" Section

### ISSUE THREAD

**Issue by GenevaS** [MaXiaoye/cas741#35]
I believe that the "Uses" section here is supposed to refer to the modules that you are going to implement (and are therefore defined in the MIS). For example, your ```ObjCutModule``` uses your ```InputModule```, ```DisAirCalcModule```, and ```DisGroCalcModule``` modules.

This occurs in other sections in your document aside from the "Uses" and it makes it difficult to know how your MIS descriptions relate to each other.

**Comment by MaXiaoye** [comment]
Update Figure in 8e56854f9b5f9a68da98ac246bd54e4ecd997ef1
