### ISSUE TITLE
MIS: Distinct Exception Labels

### ISSUE THREAD

**Issue by GenevaS** [MaXiaoye/cas741#38]
Rather than having one exception class that covers multiple values, it would make it easier to provide error feedback if you had a unique label for each situation (e.g. Rather than saying ```InvalidCoorException``` for all coordinates, use ```InvalidXCoorException```, ```InvalidYCoorException```, and ```InvalidZCoorException```).

**Comment by MaXiaoye** [comment]
Thank you for this advice ! :)
Fixed in 39f790ab5baa1a612643c8b392ed894a865307bb
