### ISSUE TITLE
MIS: Pieces Initialization Module Access Routine Semantics

### ISSUE THREAD

**Issue by GenevaS** [MaXiaoye/cas741#39]
There does not appear to be an access routine definition here. Did you mean to say that the logic written here is for the ```PieceObj()``` routine?

Aside: Many of the mathematical operators in your pseudo code were not formatted correctly by LaTeX. You might need to wrap it in a math environment like ```$<your code here>$``` or the ```listings``` package.

**Comment by MaXiaoye** [comment]
Fixed in d41c42bffcb30695686c5f9e681565a433f122a4
