### ISSUE TITLE
SRS review

### ISSUE THREAD

**Issue by MaXiaoye** [MaXiaoye/cas741#4]
Dear professor Smith,

Please kindly review my SRS.
I will improve it as your comments.
Thanks !

https://github.com/MaXiaoye/cas741/blob/master/Doc/SRS/SRS.pdf

Best regards,
Marshall

**Comment by smiths** [comment]
Hello Marshall.  I'm sorry, but your request is too open ended.  I don't have time to read over everyone's draft documents, so it would be unfair to go through your entire document.  Can you be more specific in your request?  You can look at Geneva's issue tracker for an example of questions of the appropriate scope.

https://github.com/GenevaS/CAS741/issues?q=is%3Aissue+is%3Aclosed
