### ISSUE TITLE
MIS: Referring to MG Modules Instead of the MIS Modules

### ISSUE THREAD

**Issue by GenevaS** [MaXiaoye/cas741#42]
The module references in the MIS should refer to other modules in the MIS instead of referencing the MG. I think it is a good idea to tell readers which MG module you are writing the specification for in its introduction, but after that the MG should not be referred to.

For example, you do not have a section in your MIS that specifies the "Hardware-Hiding Module", yet you reference it in the MIS for the "Input Module" specification. This makes it difficult to see the intended structure of your implementation.

**Comment by MaXiaoye** [comment]
Add section reference in MIS d41c42bffcb30695686c5f9e681565a433f122a4
