### ISSUE TITLE
Content organization of theoretical  models(TM), general definitions(GD), data definitions(DD) and instance models(IM). 

### ISSUE THREAD

**Issue by MaXiaoye** [MaXiaoye/cas741#5]
Dear prefessor Smith,

I am sorry my previous issue is too open ended !
Thank you for the link to the good example ! :)

Actually I also have some questions about relationships between TM,GD,DD and IM.
In my doc, I put energy transformation laws in TM, which is general law of my project; equation of uniformly accelerated motion and definition of kinetic friction in DD. They are needed to build IM; And I put equations for detailed calculation of output in IM. 

So that I don't have any content in GD part
Because I consider my DDs don't need to be built by deriving from more detailed equations.

https://github.com/MaXiaoye/cas741/blob/master/Doc/SRS/SRS.pdf

Can I organize these parts like this ?
Thank you !

Best Regards,
Marshall

**Comment by smiths** [comment]
Hello @MaXiaoye.  You are fine to not use the GD part.  As you have done, you should explicitly include the section, but then say that there are no general definitions for the current problem.

For your DD1 you should say what assumptions are needed for this equation.  You should also explain how it is derived from the equation for acceleration.  Looking at it now,  you really should give the relationship between position, velocity and acceleration.  You could make this a data definition.

**Comment by MaXiaoye** [comment]
Dear Dr. Smith,

Thank you for the comments !
I update GD by explicitly saying no GD for this problem
And in DD1, I add a subsection containing the derivation of how to derive the equation from relationship of position, velocity and acceleration.

https://github.com/MaXiaoye/cas741/blob/master/Doc/SRS/SRS.pdf

Best Regards,
Marshall

**Comment by smiths** [comment]
Sounds good!
