### ISSUE TITLE
SRS:   Unnecessary goal statement

### ISSUE THREAD

**Issue by palmerst** [MaXiaoye/cas741#7]
Your first goal statement "Calculate initial status including pieces generation and initial speed of each piece" seems like an intermediate step in your software, not a goal.

**Comment by MaXiaoye** [comment]
Hi Steven,

Actually I make this as a goal statement because generation of pieces is one separate part.
However yes it is indeed an intermediate step.
I will measure it and modify if it is necessary.

Best Regards,
Marshall
