### ISSUE TITLE
SRS:  Conflicting assumption

### ISSUE THREAD

**Issue by palmerst** [MaXiaoye/cas741#9]
In A4 you state "Initial kinetic energy and potential energy of target object are zero."   In R2, however, you state that v0 = E * 10.  This conflicts with A4 (initial kinetic energy will not be zero unless E is zero).  The initial gravitational potential energy will not be zero either unless the object is always at the reference height used for calculating gravitational potential (but Z is one of your inputs so this doesn't seem to be the case).

**Comment by MaXiaoye** [comment]
Hi Steven,

In A4, it is the status before explosion.
v0 in following content is the initial speed after explosion happens.
So I believe there isn't a conflict between them.：）

Best Regards,
Marshall
